 //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJAutos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDB
    {
        public int Id { get; set; }
        public string CarId { get; set; }
        public string UserId { get; set; }
        public string RegNo { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Colour { get; set; }
        public string PicturePath { get; set; }
    }
}
