//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJAutos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JJAutosDBEntities1 : DbContext
    {
        public JJAutosDBEntities1()
            : base("name=JJAutosDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<AdminDB> AdminDBs { get; set; }
        public virtual DbSet<CarDB> CarDBs { get; set; }
        public virtual DbSet<QouteDB> QouteDBs { get; set; }
        public virtual DbSet<UserDB> UserDBs { get; set; }
    }
}
