//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJAutos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QouteDB
    {
        public int Id { get; set; }
        public string QouteId { get; set; }
        public string CarId { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> DateBooking { get; set; }
        public Nullable<int> IsDone { get; set; }
        public Nullable<decimal> TotalUpper { get; set; }
        public Nullable<decimal> TotalLower { get; set; }
        public Nullable<int> Maintanance { get; set; }
        public Nullable<int> RepairCheckup { get; set; }
        public Nullable<int> TyreChange { get; set; }
        public Nullable<int> ClutchCheckup { get; set; }
        public Nullable<int> EngineCheckup { get; set; }
        public Nullable<int> BreakCheckup { get; set; }
        public Nullable<int> SuspensionCheckup { get; set; }
        public Nullable<int> FullFluidChange { get; set; }
        public string Notes { get; set; }
    }
}
